### ISSUE TITLE
Unable to clear a warp page

### ISSUE THREAD

**Issue by Dissgruntled** [ferreusveritas/WarpBook#3]
Warpbook-1.12.2-3.2.0
Forge 1.12.2 - 14.23.5.2807

According to the mod description - "Sneak+right click will clear the page." Unfortunately this isn't working. It just teleports to the page destination same as right-click.

**Comment by Azumgi** [comment]
According to the maintainer's comment [here](https://minecraft.curseforge.com/projects/warp-book?comment=86), it was fixed, but the last commit was 2 days prior to that comment. If you look at @ferreusveritas's profile, it was the last time they were active on github and didn't push changes. I guess, something happened. Hope, they are okay.

**Comment by ferreusveritas** [comment]
Pages are permanent and can't be cleared.  Unfortunately the mod description was out of date.  It's been updated.
